/**
 * Tailwind build config — replaces the Tailwind Play CDN (cdn.tailwindcss.com),
 * which compiled CSS in the browser on every page load and made the site slow.
 * The theme below mirrors the inline `tailwind.config` that used to live in
 * views/partials/head.ejs. Rebuild with: npm run build:css
 */
module.exports = {
  darkMode: 'class',
  content: [
    './views/**/*.ejs',
    './public/**/*.js',
    './src/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fcf9f3',
        surface: '#fcf9f3',
        'surface-bright': '#fcf9f3',
        'surface-dim': '#dcdad4',
        'surface-variant': '#e5e2dc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ed',
        'surface-container': '#f0eee8',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e5e2dc',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#44474d',
        'on-background': '#1c1c18',
        'inverse-surface': '#31312d',
        'inverse-on-surface': '#f3f0ea',
        outline: '#74777e',
        'outline-variant': '#c4c6ce',
        primary: '#071d3a',
        'on-primary': '#ffffff',
        'primary-container': '#071d3a',
        'on-primary-container': '#7386a8',
        'on-primary-fixed': '#051b38',
        'on-primary-fixed-variant': '#354766',
        'inverse-primary': '#b4c7ec',
        secondary: '#b8861b',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc355',
        'on-secondary-container': '#725000',
        'secondary-fixed': '#ffdea9',
        'secondary-fixed-dim': '#f6bd50',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5e4100',
        tertiary: '#00030d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#001c43',
        'on-tertiary-container': '#6a85bb',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'dark-background': '#111318',
        'dark-surface': '#1a1c21',
        'dark-surface-dim': '#111318',
        'dark-surface-bright': '#3f4046',
        'dark-surface-container-lowest': '#0c0e13',
        'dark-surface-container-low': '#1a1c21',
        'dark-surface-container': '#1e2025',
        'dark-surface-container-high': '#282a30',
        'dark-surface-container-highest': '#33353b',
        'dark-on-surface': '#e2e2e6',
        'dark-on-surface-variant': '#c2c2c8',
        'dark-outline': '#8c8e94',
        'dark-outline-variant': '#424449',
        'dark-primary': '#aec3e8',
        'dark-on-primary': '#1a2f4e',
        'dark-primary-container': '#2f4567',
        'dark-on-primary-container': '#d2e1ff',
        'dark-secondary': '#f0c04a',
        'dark-on-secondary': '#3d2b00',
        'dark-secondary-container': '#5e4100',
        'dark-on-secondary-container': '#ffdea9',
        'dark-error': '#ffb4ab',
        'dark-on-error': '#690005',
        'dark-error-container': '#93000a',
        'dark-on-error-container': '#ffdad6',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '9999px' },
      spacing: { 'container-max': '1280px', gutter: '24px', 'margin-desktop': '64px', unit: '8px', 'margin-mobile': '20px' },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        headline: ['Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif'],
        tagline: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        tagline: ['14px', { lineHeight: '20px', letterSpacing: '0.15em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
