/**
 * Seed: academic programs.
 * Idempotent — clears and reinserts the canonical program catalogue.
 */
exports.seed = async function (knex) {
  await knex('programs').del();

  const now = knex.fn.now();
  await knex('programs').insert([
    {
      slug: 'msc-global-leadership',
      title: 'MSc Global Leadership',
      level: 'Masters',
      school: 'School of Global Leadership',
      credential: 'Master of Science',
      summary:
        'Equip yourself to lead organisations, churches and communities across cultures with integrity, vision and a global perspective.',
      description:
        'The MSc Global Leadership prepares experienced professionals and ministry leaders to navigate complex, cross-cultural environments. Drawing on Christian principles of servant leadership, the programme blends strategic management, organisational behaviour, ethics and missional thinking. Students complete a capstone leadership project applied to their own context.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-program-leadership-park-v2.webp',
      icon: 'public',
      featured: true,
      published: true,
      sort_order: 1,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'ma-postcolonial-theology',
      title: 'MA Post-Colonial Theology',
      level: 'Masters',
      school: 'School of Global Theology',
      credential: 'Master of Arts',
      summary:
        'Engage theology through the lens of diaspora, migration and the global majority church to serve a changing world.',
      description:
        'This programme examines Scripture, tradition and contemporary theology from post-colonial and diaspora perspectives. Students explore migration, identity, justice and mission, equipping them to minister effectively within multicultural and diaspora communities.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 6800,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-program-theology-living-room-v2.webp',
      icon: 'menu_book',
      featured: true,
      published: true,
      sort_order: 2,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'ba-theology-ministry',
      title: 'BA Theology & Ministry',
      level: 'Undergraduate',
      school: 'School of Global Theology',
      credential: 'Bachelor of Arts',
      summary:
        'A foundational degree in biblical studies, theology and practical ministry for the next generation of Christian leaders.',
      description:
        'The BA Theology & Ministry provides a thorough grounding in biblical languages, church history, systematic theology and pastoral practice. Designed for flexible online study, it equips students for ordained ministry, missions and lay leadership.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-video-lesson-home.webp',
      icon: 'church',
      featured: false,
      published: true,
      sort_order: 3,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-church-leadership',
      title: 'Diploma in Church Leadership',
      level: 'Diploma',
      school: 'School of Global Leadership',
      credential: 'Undergraduate Diploma',
      summary:
        'Develop practical leadership skills to grow and shepherd a healthy, mission-focused local church.',
      description:
        'This vocational diploma focuses on the practicalities of leading a local congregation — preaching, discipleship, governance, finance and pastoral care — within a sound theological framework.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2800,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-teacher-living-room-v2.webp',
      icon: 'diversity_3',
      featured: false,
      published: true,
      sort_order: 4,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-community-leadership',
      title: 'Diploma in Community Leadership',
      level: 'Diploma',
      school: 'School of Global Leadership',
      credential: 'Undergraduate Diploma',
      summary:
        'Lead transformational change in diaspora and local communities through faith-driven service.',
      description:
        'Equips community workers, charity leaders and volunteers with the skills to mobilise people, manage projects and create lasting social impact rooted in Christian values.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2800,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-courtyard-learning.webp',
      icon: 'groups',
      featured: false,
      published: true,
      sort_order: 5,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'msc-business-administration',
      title: 'MBA — Faith-Led Business',
      level: 'Masters',
      school: 'School of Business & Enterprise',
      credential: 'Master of Business Administration',
      summary:
        'Lead enterprises with integrity, combining rigorous business strategy with a Christian ethic of stewardship.',
      description:
        'A practical MBA for entrepreneurs and managers who want to build profitable, ethical organisations. Covers strategy, finance, marketing, operations and ethical leadership, with a focus on the diaspora economy.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7600,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-program-mba-home-v2.webp',
      icon: 'business_center',
      featured: true,
      published: true,
      sort_order: 6,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-diaspora-mission',
      title: 'Certificate in Diaspora Care & Mission',
      level: 'Certificate',
      school: 'School of Global Theology',
      credential: 'Certificate of Higher Education',
      summary:
        'A short, accessible entry point into cross-cultural mission and pastoral care for diaspora communities.',
      description:
        'This certificate introduces the theology and practice of diaspora mission — welcoming, discipling and serving migrant and refugee communities with compassion and cultural sensitivity.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-admissions-video.webp',
      icon: 'volunteer_activism',
      featured: false,
      published: true,
      sort_order: 7,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'phd-theology',
      title: 'PhD in Theology',
      level: 'Doctorate',
      school: 'School of Global Theology',
      credential: 'Doctor of Philosophy',
      summary:
        'Undertake original, supervised research that contributes to global theological scholarship.',
      description:
        'A research doctorate supervised by experienced faculty. Candidates produce an original thesis on a topic in theology, biblical studies or mission, contributing to the academy and the global church.',
      duration: '4–6 years (online, by research)',
      study_mode: 'Online',
      tuition: 4200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-accreditation-park-v2.webp',
      icon: 'school',
      featured: false,
      published: true,
      sort_order: 8,
      created_at: now,
      updated_at: now,
    },
  ]);
};
