/**
 * Seed: academic programs.
 * Idempotent — clears and reinserts the canonical program catalogue.
 */
exports.seed = async function (knex) {
  await knex('programs').del();

  const now = knex.fn.now();
  await knex('programs').insert([
    {
      slug: 'certificate-biblical-studies',
      title: 'Certificate in Biblical Studies',
      level: 'Certificate',
      school: 'School of Global Theology',
      credential: 'Certificate of Higher Education',
      summary: 'A foundational certificate on Scripture, Bible study methods and Christian doctrine.',
      description: 'Study the Bible’s structure, literary genres and theological themes with this introductory certificate. Ideal for new students, lay leaders and church staff who want a strong biblical foundation.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-research-library.webp',
      icon: 'menu_book',
      featured: false,
      published: true,
      sort_order: 1,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-christian-ministry',
      title: 'Certificate in Christian Ministry',
      level: 'Certificate',
      school: 'School of Ministry Practice',
      credential: 'Certificate of Higher Education',
      summary: 'Practical ministry skills for service, teaching and church life.',
      description: 'Develop leadership, preaching, pastoral care and discipleship skills for effective Christian ministry. This certificate is designed for emerging leaders, volunteers and church workers.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1250,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-cafe-study.webp',
      icon: 'church',
      featured: false,
      published: true,
      sort_order: 2,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-pastoral-care',
      title: 'Certificate in Pastoral Care',
      level: 'Certificate',
      school: 'School of Pastoral Studies',
      credential: 'Certificate of Higher Education',
      summary: 'Care skills for counseling, crisis support and spiritual presence.',
      description: 'Learn the essentials of pastoral care, active listening and spiritual accompaniment. This certificate equips students to support individuals, families and congregations with compassion.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1250,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-library-research.webp',
      icon: 'support',
      featured: false,
      published: true,
      sort_order: 3,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-chaplaincy-spiritual-care',
      title: 'Certificate in Chaplaincy and Spiritual Care',
      level: 'Certificate',
      school: 'School of Pastoral Studies',
      credential: 'Certificate of Higher Education',
      summary: 'Foundational training for chaplains in hospitals, prisons, schools and organisations.',
      description: 'Prepare to offer spiritual presence, interfaith sensitivity and pastoral care in chaplaincy settings. The certificate focuses on ethics, crisis ministry and reflective practice.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1300,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-outdoor-mentor.webp',
      icon: 'local_hospital',
      featured: false,
      published: true,
      sort_order: 4,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-christian-leadership',
      title: 'Certificate in Christian Leadership',
      level: 'Certificate',
      school: 'School of Global Leadership',
      credential: 'Certificate of Higher Education',
      summary: 'Principles of Christ-centred leadership for church and community.',
      description: 'Study leadership from a biblical perspective, including team formation, vision casting and character development. This certificate helps leaders serve with humility and strategic clarity.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1250,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-teacher-online-classroom.webp',
      icon: 'diversity_3',
      featured: false,
      published: true,
      sort_order: 5,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-missions-diaspora-ministry',
      title: 'Certificate in Missions and Diaspora Ministry',
      level: 'Certificate',
      school: 'School of Global Theology',
      credential: 'Certificate of Higher Education',
      summary: 'Engage diaspora communities with mission strategy, cultural intelligence and gospel partnership.',
      description: 'This certificate explores migration, diaspora identity and mission practice. Students learn to build culturally effective ministry and sustainable church partnerships.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1300,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-east-africa-hero.webp',
      icon: 'public',
      featured: false,
      published: true,
      sort_order: 6,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-church-administration',
      title: 'Certificate in Church Administration',
      level: 'Certificate',
      school: 'School of Ministry Practice',
      credential: 'Certificate of Higher Education',
      summary: 'Administration, finance and governance skills for healthy church operations.',
      description: 'Learn budgeting, governance, events coordination and volunteer management for church settings. This certificate is ideal for church administrators and lay leaders.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-community.webp',
      icon: 'admin_panel_settings',
      featured: false,
      published: true,
      sort_order: 7,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'certificate-prayer-discipleship-spiritual-formation',
      title: 'Certificate in Prayer, Discipleship and Spiritual Formation',
      level: 'Certificate',
      school: 'School of Spiritual Formation',
      credential: 'Certificate of Higher Education',
      summary: 'Deepen your prayer life and disciple others through spiritual formation practices.',
      description: 'This certificate teaches spiritual disciplines, prayer frameworks and discipleship rhythms. Students learn how to nurture their own devotion while mentoring others in spiritual growth.',
      duration: '6 months (online)',
      study_mode: 'Online',
      tuition: 1200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-teacher-living-room-v2.webp',
      icon: 'self_improvement',
      featured: false,
      published: true,
      sort_order: 8,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-biblical-studies',
      title: 'Diploma in Biblical Studies',
      level: 'Diploma',
      school: 'School of Global Theology',
      credential: 'Undergraduate Diploma',
      summary: 'A deeper study of Old and New Testament themes, books and theology.',
      description: 'This diploma examines biblical theology, historical context and interpretive methods for both Testaments. Students develop a rich understanding of the Bible’s unity and message.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2800,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-program-living-room-v2.webp',
      icon: 'menu_book',
      featured: false,
      published: true,
      sort_order: 9,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-christian-ministry',
      title: 'Diploma in Christian Ministry',
      level: 'Diploma',
      school: 'School of Ministry Practice',
      credential: 'Undergraduate Diploma',
      summary: 'A practical diploma for ministry leaders, pastors and church workers.',
      description: 'This diploma covers preaching, pastoral care, discipleship and mission. Students gain hands-on ministry tools with a strong theological foundation.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2900,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-workshop-lesson.webp',
      icon: 'people',
      featured: false,
      published: true,
      sort_order: 10,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-chaplaincy-pastoral-care',
      title: 'Diploma in Chaplaincy and Pastoral Care',
      level: 'Diploma',
      school: 'School of Pastoral Studies',
      credential: 'Undergraduate Diploma',
      summary: 'Applied chaplaincy skills for pastoral care in secular and sacred environments.',
      description: 'This diploma equips students for chaplaincy and pastoral care roles in hospitals, prisons, schools and community organisations. It combines theology, ethics and practical care.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2900,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-accreditation-lifestyle.webp',
      icon: 'local_hospital',
      featured: false,
      published: true,
      sort_order: 11,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-christian-leadership',
      title: 'Diploma in Christian Leadership',
      level: 'Diploma',
      school: 'School of Global Leadership',
      credential: 'Undergraduate Diploma',
      summary: 'Advance your leadership skills for leading teams, churches and faith initiatives.',
      description: 'This diploma combines leadership theory, team development and practical church leadership skills. It is ideal for church elders, ministry directors and community leaders.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2900,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-intake-male-home-v2.webp',
      icon: 'diversity_3',
      featured: false,
      published: true,
      sort_order: 12,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-theology-ministry',
      title: 'Diploma in Theology and Ministry',
      level: 'Diploma',
      school: 'School of Global Theology',
      credential: 'Undergraduate Diploma',
      summary: 'A balanced diploma in theological reflection and practical ministry.',
      description: 'This diploma integrates biblical theology with ministry practice, helping students connect doctrine to daily pastoral and church leadership work.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2800,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-online-learning.webp',
      icon: 'school',
      featured: false,
      published: true,
      sort_order: 13,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-missions-global-christianity',
      title: 'Diploma in Missions and Global Christianity',
      level: 'Diploma',
      school: 'School of Global Theology',
      credential: 'Undergraduate Diploma',
      summary: 'Explore contemporary mission, diaspora church growth and global Christian movements.',
      description: 'This diploma examines mission practice, global Christianity and diaspora ministry strategies. Students learn to serve diverse communities with cross-cultural competence.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2800,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-east-africa-online-learning.webp',
      icon: 'public',
      featured: false,
      published: true,
      sort_order: 14,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'diploma-pastoral-counselling-ministry',
      title: 'Diploma in Pastoral Counselling for Ministry',
      level: 'Diploma',
      school: 'School of Pastoral Studies',
      credential: 'Undergraduate Diploma',
      summary: 'Counselling approaches for ministry contexts, trauma care and spiritual support.',
      description: 'Combining theology and practical counselling, this diploma helps ministers support people through grief, conflict and spiritual struggle.',
      duration: '1 year (online)',
      study_mode: 'Online',
      tuition: 2900,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-admissions-advisor.webp',
      icon: 'psychology',
      featured: false,
      published: true,
      sort_order: 15,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'master-christian-theology',
      title: 'Master of Arts in Christian Theology',
      level: 'Masters',
      school: 'School of Global Theology',
      credential: 'Master of Arts in Christian Theology',
      summary: 'Advanced theological study for ministry leaders and scholars.',
      description: 'This master’s programme explores doctrinal theology, biblical interpretation and contemporary theological issues. Students build the skills for teaching, research and advanced ministry.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-program-theology-living-room-v2.webp',
      icon: 'menu_book',
      featured: true,
      published: true,
      sort_order: 16,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'master-christian-ministry',
      title: 'Master of Arts in Christian Ministry',
      level: 'Masters',
      school: 'School of Ministry Practice',
      credential: 'Master of Arts in Christian Ministry',
      summary: 'Graduate-level ministry training for holistic pastoral leadership.',
      description: 'Designed for experienced ministry leaders, this programme integrates theology, pastoral practice and leadership development for the contemporary church.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-program-female-home-v2.webp',
      icon: 'people',
      featured: true,
      published: true,
      sort_order: 17,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'master-christian-leadership',
      title: 'Master of Arts in Christian Leadership',
      level: 'Masters',
      school: 'School of Global Leadership',
      credential: 'Master of Arts in Christian Leadership',
      summary: 'Transformational leadership training for church and mission contexts.',
      description: 'This programme focuses on strategic leadership, innovation and character formation for Christian leaders across organisations and ministries.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-program-leadership-park-v2.webp',
      icon: 'diversity_3',
      featured: true,
      published: true,
      sort_order: 18,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'master-chaplaincy-spiritual-care',
      title: 'Master of Arts in Christian Chaplaincy and Spiritual Care',
      level: 'Masters',
      school: 'School of Pastoral Studies',
      credential: 'Master of Arts in Christian Chaplaincy and Spiritual Care',
      summary: 'Advanced chaplaincy training for complex care environments.',
      description: 'This master’s programme develops expert chaplains who can provide spiritual care in hospitals, prisons, schools and secular settings with pastoral wisdom and professional competence.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-research-lifestyle.webp',
      icon: 'local_hospital',
      featured: true,
      published: true,
      sort_order: 19,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'master-pastoral-care-counselling-ministry',
      title: 'Master of Arts in Christian Pastoral Care and Counselling for Ministry',
      level: 'Masters',
      school: 'School of Pastoral Studies',
      credential: 'Master of Arts in Christian Pastoral Care and Counselling for Ministry',
      summary: 'Counselling and pastoral care training for ministry professionals.',
      description: 'This programme combines theology and counselling practice, equipping ministers to support emotional and spiritual health in individuals and families.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-courtyard-learning.webp',
      icon: 'psychology',
      featured: true,
      published: true,
      sort_order: 20,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'master-missions-diaspora-ministry',
      title: 'Master of Arts in Christian Missions and Diaspora Ministry',
      level: 'Masters',
      school: 'School of Global Theology',
      credential: 'Master of Arts in Christian Missions and Diaspora Ministry',
      summary: 'Advanced study in mission, migration and diaspora church leadership.',
      description: 'This programme prepares students to lead mission initiatives among diaspora communities, balancing cultural insight with theological clarity.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-intake-lifestyle.webp',
      icon: 'public',
      featured: true,
      published: true,
      sort_order: 21,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'bachelor-biblical-studies',
      title: 'Bachelor of Arts in Christian Biblical Studies',
      level: 'Undergraduate',
      school: 'School of Global Theology',
      credential: 'Bachelor of Arts in Christian Biblical Studies',
      summary: 'A broad undergraduate degree in biblical languages, literature and theology.',
      description: 'This degree offers rigorous study of the Old and New Testament, biblical theology and interpretive methods, preparing students for ministry, teaching and further theological study.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-video-lesson-home.webp',
      icon: 'menu_book',
      featured: false,
      published: true,
      sort_order: 22,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'bachelor-christian-ministry',
      title: 'Bachelor of Arts in Christian Ministry',
      level: 'Undergraduate',
      school: 'School of Ministry Practice',
      credential: 'Bachelor of Arts in Christian Ministry',
      summary: 'Undergraduate training for the next generation of ministry leaders.',
      description: 'This degree combines theology, leadership and practical ministry skills. Students gain preparation for paid and volunteer ministry roles in churches and mission organisations.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-program-lifestyle.webp',
      icon: 'people',
      featured: false,
      published: true,
      sort_order: 23,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'bachelor-christian-leadership',
      title: 'Bachelor of Arts in Christian Leadership',
      level: 'Undergraduate',
      school: 'School of Global Leadership',
      credential: 'Bachelor of Arts in Christian Leadership',
      summary: 'Leadership formation for Christian thinkers, organisers and church practitioners.',
      description: 'This degree teaches leadership theory, ethics and group dynamics from a Christian perspective, preparing graduates to lead churches, nonprofits and community networks.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-accreditation-east-africa.webp',
      icon: 'diversity_3',
      featured: false,
      published: true,
      sort_order: 24,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'bachelor-chaplaincy-pastoral-care',
      title: 'Bachelor of Arts in Christian Chaplaincy and Pastoral Care',
      level: 'Undergraduate',
      school: 'School of Pastoral Studies',
      credential: 'Bachelor of Arts in Christian Chaplaincy and Pastoral Care',
      summary: 'Undergraduate training for spiritual care, counselling and chaplaincy work.',
      description: 'This degree develops compassionate pastoral ministers who can serve in chaplaincy, counselling and church care ministries with maturity and insight.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-intake-east-africa.webp',
      icon: 'local_hospital',
      featured: false,
      published: true,
      sort_order: 25,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'bachelor-theology-ministry',
      title: 'Bachelor of Arts in Christian Theology and Ministry',
      level: 'Undergraduate',
      school: 'School of Global Theology',
      credential: 'Bachelor of Arts in Christian Theology and Ministry',
      summary: 'A broad degree in theology, biblical studies and ministry formation.',
      description: 'This degree equips students for ministry, teaching and mission with a strong theological foundation and practical experience.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-research-east-africa.webp',
      icon: 'school',
      featured: false,
      published: true,
      sort_order: 26,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'bachelor-missions-global-christianity',
      title: 'Bachelor of Arts in Christian Missions and Global Christianity',
      level: 'Undergraduate',
      school: 'School of Global Theology',
      credential: 'Bachelor of Arts in Christian Missions and Global Christianity',
      summary: 'Study global mission, diaspora church and cross-cultural ministry practice.',
      description: 'This degree prepares students to serve across cultures and contexts, with theological insight into global Christianity and mission strategy.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-program-east-africa.webp',
      icon: 'public',
      featured: false,
      published: true,
      sort_order: 27,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'doctorate-christian-ministry',
      title: 'Doctor of Philosophy in Christian Ministry',
      level: 'Doctorate',
      school: 'School of Global Theology',
      credential: 'Doctor of Philosophy in Christian Ministry',
      summary: 'Research doctorate for advanced scholarship in Christian ministry.',
      description: 'This PhD programme develops advanced research in Christian ministry. Students complete doctoral research, a defended dissertation and an original contribution to ministry scholarship.',
      duration: '3–4 years (online, part-time)',
      study_mode: 'Online',
      tuition: 8200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-newsroom.webp',
      icon: 'school',
      featured: false,
      published: true,
      sort_order: 28,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'doctorate-practical-theology',
      title: 'Doctor of Philosophy in Christian Practical Theology',
      level: 'Doctorate',
      school: 'School of Global Theology',
      credential: 'Doctor of Philosophy in Christian Practical Theology',
      summary: 'Research doctorate in Christian practical theology and ministry.',
      description: 'This PhD programme explores the intersection of theology and practice through rigorous research. Students complete a defended dissertation that makes an original contribution to Christian practical theology.',
      duration: '3–4 years (online, part-time)',
      study_mode: 'Online',
      tuition: 8200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-news-accreditation-park-v2.webp',
      icon: 'school',
      featured: false,
      published: true,
      sort_order: 29,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'doctorate-chaplaincy-spiritual-care',
      title: 'Doctor of Philosophy in Christian Chaplaincy and Spiritual Care',
      level: 'Doctorate',
      school: 'School of Pastoral Studies',
      credential: 'Doctor of Philosophy in Christian Chaplaincy and Spiritual Care',
      summary: 'Research doctorate in Christian chaplaincy and spiritual care.',
      description: 'This PhD programme develops advanced research in Christian chaplaincy and spiritual care. Students complete a defended dissertation and an original contribution to the field.',
      duration: '3–4 years (online, part-time)',
      study_mode: 'Online',
      tuition: 8200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-east-africa-community.webp',
      icon: 'local_hospital',
      featured: false,
      published: true,
      sort_order: 30,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'doctorate-christian-leadership',
      title: 'Doctor of Philosophy in Christian Leadership',
      level: 'Doctorate',
      school: 'School of Global Leadership',
      credential: 'Doctor of Philosophy in Christian Leadership',
      summary: 'Research doctorate in Christian leadership and organisational transformation.',
      description: 'This PhD programme develops original research in Christian leadership, organisational transformation and mission innovation, culminating in a defended dissertation.',
      duration: '3–4 years (online, part-time)',
      study_mode: 'Online',
      tuition: 8200,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-program-mba-home-v2.webp',
      icon: 'diversity_3',
      featured: false,
      published: true,
      sort_order: 31,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'ba-theology-ministry',
      title: 'BA Theology & Ministry',
      level: 'Undergraduate',
      school: 'School of Global Theology',
      credential: 'Bachelor of Arts',
      summary: 'A foundational degree in biblical studies, theology and practical ministry for the next generation of Christian leaders.',
      description: 'The BA Theology & Ministry provides a thorough grounding in biblical languages, church history, systematic theology and pastoral practice. Designed for flexible online study, it equips students for ordained ministry, missions and lay leadership.',
      duration: '3 years (online)',
      study_mode: 'Online',
      tuition: 5400,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-student-admissions-video.webp',
      icon: 'menu_book',
      featured: false,
      // Retained for historical records, but no longer offered publicly.
      published: false,
      sort_order: 32,
      created_at: now,
      updated_at: now,
    },
    {
      slug: 'msc-business-administration',
      title: 'MBA — Faith-Led Business',
      level: 'Masters',
      school: 'School of Business & Enterprise',
      credential: 'Master of Business Administration',
      summary: 'Lead enterprises with integrity, combining rigorous business strategy with a Christian ethic of stewardship.',
      description: 'A practical MBA for entrepreneurs and managers who want to build profitable, ethical organisations. Covers strategy, finance, marketing, operations and ethical leadership, with a focus on the diaspora economy.',
      duration: '2 years (part-time, online)',
      study_mode: 'Online',
      tuition: 7600,
      tuition_currency: 'GBP',
      image_url: '/img/generated/gdcu-east-africa-admissions.webp',
      icon: 'business_center',
      // The general MBA is not part of the religious-vocation catalogue.
      // Keep its record for historical enrolments, but do not offer it publicly.
      featured: false,
      published: false,
      sort_order: 33,
      created_at: now,
      updated_at: now,
    },
  ]);

  // Existing programme-level curriculum values in semester credits. The
  // general-education allocation is intentionally left for academic review.
  await knex('programs').whereIn('level', ['Undergraduate']).update({ semester_credits: 120 });
  await knex('programs').whereIn('level', ['Masters']).update({ semester_credits: 60 });
  await knex('programs').whereIn('level', ['Doctorate']).update({ semester_credits: 60 });
  await knex('programs').whereIn('level', ['Diploma']).update({ semester_credits: 60 });
  await knex('programs').whereIn('level', ['Certificate']).update({ semester_credits: 30 });
};
